# Get TensorFlow warnings out the way so output is more coherent
library(sgmcmc)
quickSess = tf$Session()
message("\n")
source("gaussMix.R")
message("Running simulations for Gaussian Mixture")
runSimulations()
plotGM()
source("logReg.R")
message("Running simulations for Logistic Regression")
runSimulations()
plotLogReg()
source("nn.R")
message("Running simulations for Bayesian Neural Network")
runSimulations()
plotNN()
